### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ajjxf** [michthom/MIDI-to-CNC#11]
could you please explain the way to use it more exactly?   thanks :)

**Comment by michthom** [comment]
Sorry, I'm not maintaining this repo actively, and if you're not happy with the guidance in the README then it's probably not for you. There are more recent forks of this code such as https://github.com/Moederbeer/MIDI-to-CNC and perhaps those maintainers might have time to help you get started?

**Comment by ajjxf** [comment]
ok thanks  :)
