### ISSUE TITLE
Output M300 tunes instead of axis movement?

### ISSUE THREAD

**Issue by pyr0ball** [michthom/MIDI-to-CNC#8]
Since most 3D printers come with a buzzer and marlin has supported beep tones via M300 for a long time, I've been hoping for a midi conversion tool that worked with that. Would it be possible to modify this to do that?

**Comment by michthom** [comment]
I no longer have any 3D printers available to me, so I look forward to any patches, but I won't be developing the software myself, sorry.

**Comment by pyr0ball** [comment]
Okidokie, thanks for checking in! I'll fork and PR if/when I have some time
to work on it
